exports.list = [
  "What animal is your Patronus?",
  "If you ruled the world, what laws would you make?",
  "What was your last dream about?",
  "What would you do if you won the lottery?",
  "What does your dream house look like?",
  "What was your favorite vacation?",
  "If you could go back in time to change one thing what would it be?",
  "What's the greatest invention of all time?",
  "Have you ever been admitted to the hospital?",
  "Have you ever had any brushes with the law?",
  "What's the best practical joke you've played on someone?",
  "What's the best practical joke someone's pulled on you?",
  "What is your best achievement to date?",
  "If you could live anywhere, where would it be?",
  "What's your favorite song?",
  "What's your favorite word (inappropriate or otherwise)?",
  "What's the longest period of time you've gone without sleep?",
  "Do you have any scars?",
  "If you could change anything about yourself what would it be?",
  "Would you rather trade some intelligence for looks or looks for intelligence?",
  "Have you ever had a secret admirer?",
  "If you could ask your future self one question, what would it be?",
  "Are you a good liar?",
  "What's your favorite joke?",
  "What's the worst present you've ever gotten?",
  "What's your favourite saying?",
  "Have you ever accidentally injured anyone?",
  "What cartoon character would you love to see in 21st century life?",
  "What's the word you use most often?",
  "What's your dream job?",
  "Which song annoys you the most?",
  "What's your first thought when you wake up?",
  "If you could steal one thing in the world, what would it be?",
  "What's your favorite Pokemon character?",
  "When did you stop believing in Santa?",
  "What's your favorite Disney movie?",
  "What's your life motto?",
  "What's the most unusual thing you've ever eaten?",
  "Do you collect anything?",
  "What thing would you like to bring back into fashion?",
  "What makes you nervous?",
  "What's the worst pickup line you've ever heard?",
  "What do you do when you forget someone's name immediately after they've introduced themselves?",
  "Have you ever been in a fight?",
  "Have you ever started a rumor?",
  "What's the most memorable rumor you've heard about yourself?",
  "Is there anything about the opposite sex you just don't understand?",
  "If you had a warning label, what would yours say?",
  "Which fictional character do you wish was real?",
  "Who was your first crush?",
  "Do you believe in destiny or free will?",
  "What's the best decision you've made so far?",
  "Who would you want to be with on a desert island?",
  "If you had to pick a new name for a week, what would it be?",
  "What is your first memory?",
  "Where did you go on your first ride on an airplane?",
  "Who was your first best friend?",
  "What was your first detention for?",
  "What would be the name of your debut solo album?",
  "What's something you get compulsive about?",
  "Have you ever stolen anything?",
  "What was the last social faux pas you made?",
  "What makes you nostalgic?",
  "What's the scariest thing you've ever done?",
  "What fairy tale character do you most associate with?",
  "What's the craziest thing you've ever done for someone?",
  "What's the best piece of advice anyone has ever given you?",
  "Do you have a Princeton bucket list?",
  "What's your favorite memory at Princeton?",
  "What building would you donate to Princeton?",
  "What is one thing you always wanted as a kid, but never got?",
  "What is the nicest thing someone else has done for you?",
  "If you could time travel, what would you do?",
  "If you went to a psychiatrist, what would he/she say you suffer from?",
  "What one thing annoys you most at a restaurant?",
  "What do Princeton students do too much of today?",
  "What would you like to spend more time doing?",
  "If you could dis-invent one thing, what would it be?",
  "How would you dispose of a dead body?", 
  "What's the most recent dream you can remember?",
  "What's something about you that people wouldn't expect?",
  "If you could change one thing about the world, what would it be?",
  "What's your favorite genre of music?",
  "If you could eat lunch with one famous person, who would it be?",
  "How are you feeling right now?",
  "What do you think about the most?",
  "Do you sing in the shower?",
  "Before Princeton, what did you want to be when you grew up?",
  "What is your best childhood memory?",
  "What's something embarrassing that happened to you?",
  "If you could live in any city in the world, where would it be?",
  "Where do you want to travel to?",
  "What's something spontaneous that you've done?",
  "If you could only eat one food for the rest of your life, what would it be?",
  "What's your biggest pet peeve?",
  "What was the happiest moment in your life?",
  "What quality about yourself do you value most?",
  "What are you most proud about in your life?",
  "What is your biggest concern about the future?",
  "What is the biggest lesson you've learned in life thus far?",
  "Do you think people can control their own destinies?",
  "How is your relationship with your parents?",
  "If you could go back and relive a day in your life, what would you change?",
  "What is the weirdest thing about you?",
  "If you could have any superpower, which one would you pick?",
  "What is the last thing you do before you go to sleep?",
  "What’s the first thing you notice when you meet someone new?",
  "What’s one of your worst habits?",
  "If your house was on fire, what's the one thing you'd want to take with you?",
  "If money was no object, what would you be doing with your life?",
  "What does your vision of a utopian society look like?",
  "If you only had one day left to live, what would you do?",
  "What's one thing that you learned this week?",
  "What was the last thing you thought about last night?",
  "What were you like as a kid?",
  "What is one thing you miss about being a kid?",
  "Do you believe in soul mates?",
  "Do you believe in love at first sight?",
  "What's one thing you'd like to change about Princeton?",
  "How was your RCA during your freshman year?"
];
